// Fit the learned bidding model: for many random deals, make one seat call
// each suit from each speaking position, play the hand out with Level 2 bots,
// and regress the caller team's hand score difference on six-card hand features.
// Writes src/games/bela/bots/bidding-model.ts.
// Usage: npx vite-node scripts/bots/learn-bidding.ts [deals=20000] [threshold=10]
import { writeFileSync } from 'node:fs';
import { SUITS } from '../../src/core/cards';
import { apply, setup } from '../../src/games/bela/engine';
import { makeBot } from '../../src/games/bela/bots';
import { ARENA_OPTIONS, playHand } from '../../src/games/bela/bots/arena';
import { bidFeatures } from '../../src/games/bela/bots/bidding';

const deals = Number(process.argv[2] ?? 20000);
const threshold = Number(process.argv[3] ?? 10);
// Possibility-only tracking (no sampling) keeps 320k playouts to about a minute.
const bot = makeBot('tracker:samples=0');
const X: number[][] = [];
const y: number[] = [];

for (let seed = 1; seed <= deals; seed++) {
  for (let position = 0; position < 4; position++) {
    for (const suit of SUITS) {
      let s = setup(ARENA_OPTIONS, 50_000 + seed);
      const seat = (s.turn + position) % 4; // ccw: speaking order is seat order
      const hand = s.hands[seat];
      for (let i = 0; i < position; i++) s = apply(s, { type: 'pass' });
      s = apply(s, { type: 'call', suit });
      const end = playHand(s, [bot, bot, bot, bot], seed * 16 + position * 4);
      const r = end.history[0];
      const team = seat % 2;
      X.push(bidFeatures(hand, suit, position));
      y.push(r.score[team] - r.score[1 - team]);
    }
  }
}

// Ridge regression via normal equations.
const d = X[0].length;
const A = Array.from({ length: d }, () => new Array(d).fill(0));
const b = new Array(d).fill(0);
for (let n = 0; n < X.length; n++) {
  for (let i = 0; i < d; i++) {
    b[i] += X[n][i] * y[n];
    for (let j = 0; j < d; j++) A[i][j] += X[n][i] * X[n][j];
  }
}
for (let i = 1; i < d; i++) A[i][i] += 1;
// Gaussian elimination.
for (let i = 0; i < d; i++) {
  let p = i;
  for (let r = i + 1; r < d; r++) if (Math.abs(A[r][i]) > Math.abs(A[p][i])) p = r;
  [A[i], A[p]] = [A[p], A[i]];
  [b[i], b[p]] = [b[p], b[i]];
  for (let r = 0; r < d; r++) {
    if (r === i) continue;
    const f = A[r][i] / A[i][i];
    for (let c = i; c < d; c++) A[r][c] -= f * A[i][c];
    b[r] -= f * b[i];
  }
}
const w = b.map((v, i) => +(v / A[i][i]).toFixed(2));

let sse = 0;
let sst = 0;
const mean = y.reduce((a, c) => a + c, 0) / y.length;
for (let n = 0; n < X.length; n++) {
  const pred = X[n].reduce((a, x, i) => a + x * w[i], 0);
  sse += (y[n] - pred) ** 2;
  sst += (y[n] - mean) ** 2;
}
const names = ['bias', 'J', '9', 'A', '10', 'K+Q', 'bela', 'low(7/8)', '3+ trumps', 'J&9', 'side A', 'side 10', 'side K', 'voids', 'first', 'dealer'];
console.log(`samples ${y.length}, R² ${(1 - sse / sst).toFixed(3)}`);
names.forEach((n, i) => console.log(n.padEnd(10), w[i]));

writeFileSync(
  'src/games/bela/bots/bidding-model.ts',
  `// Generated by scripts/bots/learn-bidding.ts (${deals} deals × 4 positions × 4 suits, Level 2 play).
// Expected hand score difference for the caller's team; R² ${(1 - sse / sst).toFixed(3)}.
// Features: ${names.join(', ')}.
export const BIDDING_MODEL = {
  threshold: ${threshold},
  weights: [${w.join(', ')}],
};
`,
);
