// Generated by scripts/bots/learn-bidding.ts (20000 deals × 4 positions × 4 suits, Level 2 play).
// Expected hand score difference for the caller's team; R² 0.103.
// Features: bias, J, 9, A, 10, K+Q, bela, low(7/8), 3+ trumps, J&9, side A, side 10, side K, voids, first, dealer.
export const BIDDING_MODEL = {
  threshold: 10,
  weights: [-130.03, 69.58, 45.49, 31.19, 25.24, 20.9, 23.64, 8.41, 22.02, 19.6, 19.33, 6.75, -0.45, 9.52, 1.89, -1.94],
};
