import type { Card as CardT, Rank, Suit } from '../../core/cards';

// Card art is generated by scripts/cards/build-hungarian-deck.mjs. Each card is its own SVG file,
// shown as an image: the artwork is detailed, and one cached file per card keeps the DOM small.
const CARD_URLS = import.meta.glob('./hungarian/cards/*.svg', { eager: true, query: '?url', import: 'default' }) as Record<string, string>;
const EMBLEM_URLS = import.meta.glob('./hungarian/emblems/*.svg', { eager: true, query: '?url', import: 'default' }) as Record<string, string>;

/** Hungarian suits paired with the French ones the engine uses. */
const SUIT_FILE: Record<Suit, string> = { hearts: 'hearts', diamonds: 'bells', clubs: 'acorns', spades: 'leaves' };
const RANK_FILE: Partial<Record<Rank, string>> = { J: 'unter', Q: 'ober', K: 'king', A: 'ace' };

/** Unter, Ober, King, Ace: the letters printed in the corners of the Hungarian cards. */
export const HUNGARIAN_RANK_LABEL: Partial<Record<Rank, string>> = { J: 'U', Q: 'O', K: 'K', A: 'A' };

export function hungarianCardUrl({ suit, rank }: CardT): string {
  const url = CARD_URLS[`./hungarian/cards/${SUIT_FILE[suit]}-${RANK_FILE[rank] ?? rank}.svg`];
  if (!url) throw new Error(`no Hungarian card art for ${rank} of ${suit}`);
  return url;
}

const emblemUrl = (suit: Suit) => EMBLEM_URLS[`./hungarian/emblems/${SUIT_FILE[suit]}.svg`];

export function HungarianFace({ card }: { card: CardT }) {
  return (
    <svg viewBox="0 0 60 84" aria-hidden="true">
      <image href={hungarianCardUrl(card)} width="60" height="84" />
    </svg>
  );
}

/** The suit's emblem from the deck, sized by the surrounding text. */
export function Emblem({ suit, className }: { suit: Suit; className?: string }) {
  return <img src={emblemUrl(suit)} alt="" className={className} draggable={false} />;
}

const preloaded: HTMLImageElement[] = [];
/** Fetches every card once, so a card played by another seat never appears blank for a moment. */
export function preloadHungarian() {
  if (preloaded.length || typeof Image === 'undefined') return;
  for (const url of [...Object.values(CARD_URLS), ...Object.values(EMBLEM_URLS)]) {
    const img = new Image();
    img.src = url;
    preloaded.push(img);
  }
}
